export const mobileReleaseInfo = {
  appName: "Medya Zekasi",
  version: "0.1.0",
  androidPackage: "com.medyazekasi.mobile",
  iosBundle: "com.medyazekasi.mobile",
  componentName: "MediaZekasiMobile",
  apiBaseUrl: "https://app.medyazekasi.com/api/v1",
  developer: {
    name: "Gokbilge",
    website: "https://gokbilge.com",
    email: "info@gokbilge.com",
    phone: "+90 312 440 18 20",
    phoneHref: "tel:+903124401820",
    address: "Mustafa Kemal Mah 2139 Cad IBK Plaza No:2 Cankaya Ankara",
  },
  highlights: [
    "Kullanici adi ve sifre ile giris",
    "Ses ve video yukleme",
    "Uygulama ici ses kaydi",
    "YouTube linki ile is olusturma",
    "Baska uygulamalardan paylasim akisi",
    "Transkript goruntuleme, kopyalama ve duzenleme",
    "Kredi bakiyesi ve hesap bilgisi",
    "Tema secimi ve sifre degistirme",
  ],
  screens: [
    "Login",
    "Home",
    "Jobs",
    "New Job",
    "Job Detail",
    "Settings",
    "Change Password",
  ],
  permissions: {
    android: [
      "Internet erisimi",
      "Mikrofon",
      "Ses ve video dosyalarini okuma",
      "Android paylasim (SEND / SEND_MULTIPLE) entegrasyonu",
    ],
    ios: [
      "Mikrofon erisimi",
      "Fotograf arsivi icinden ses/video secimi",
      "Paylasilan icerigi uygulama akisina alma",
      "App Transport Security ile guvenli ag kullanimi",
    ],
  },
  privacy: [
    "iOS privacy manifest tanimli",
    "Tracking kapali",
    "Collected data types bos tanimli",
    "JWT token yalnizca guvenli depolamada tutulur",
    "Mobil istemci yalnizca kullanicinin kendi islerine erisir",
  ],
  storeCopy: {
    subtitle: "Kurumsal medya kayitlarini mobile tasiyan is akisiniz",
    shortDescription:
      "Ses, video ve YouTube kayitlarini gonderin; islerinizi mobilde takip edin.",
    fullDescription: [
      "Medya Zekasi, kurum ici medya islerini mobil cihazlardan yonetmek isteyen ekipler icin gelistirilmis resmi mobil istemcidir.",
      "Kullanicilar mevcut kurum hesaplariyla giris yapabilir, ses ve video dosyasi yukleyebilir, uygulama icinde ses kaydi alip is olusturabilir, YouTube linki gonderebilir ve kendi islerinin durumunu takip edebilir.",
      "Tamamlanan islerde transkript metni goruntulenebilir, kopyalanabilir ve duzenlenebilir. Ayarlar ekraninda kredi bilgisi, tema secimi ve sifre degistirme gibi temel hesap islemleri yer alir.",
      "Uygulama ozellikle belediyeler, basin-yayin ekipleri, kamu kurumlari ve saha ekipleri icin hizli is olusturma ve kurumsal hafiza akisina mobil erisim saglar.",
    ],
    keywords: [
      "medya zekasi",
      "transkripsiyon",
      "kurumsal hafiza",
      "belediye",
      "kamu",
      "ses kaydi",
      "video yukleme",
      "youtubedan is olusturma",
    ],
    supportUrl: "https://medyazekasi.com/gizlilik-politikasi",
    marketingUrl: "https://medyazekasi.com/mobil-uygulama",
  },
};
