export const mobileReleaseInfo = {
  appName: "Medya Zekasi",
  version: "0.1.0",
  androidPackage: "com.medyazekasi.mobile",
  iosBundle: "com.medyazekasi.mobile",
  componentName: "MediaZekasiMobile",
  apiBaseUrl: "https://app.medyazekasi.com/api/v1",
  developer: {
    name: "Gokbilge",
    website: "https://gokbilge.com",
    email: "info@gokbilge.com",
    phone: "+90 312 440 18 20",
    phoneHref: "tel:+903124401820",
    address: "Mustafa Kemal Mah 2139 Cad IBK Plaza No:2 Cankaya Ankara",
  },
  highlights: [
    "Kullanici adi ve sifre ile giris",
    "Ses ve video yukleme",
    "Uygulama ici ses kaydi",
    "YouTube linki ile is olusturma",
    "Baska uygulamalardan paylasim akisi",
    "Transkript goruntuleme, kopyalama ve duzenleme",
    "Kredi bakiyesi ve hesap bilgisi",
    "Tema secimi ve sifre degistirme",
  ],
  screens: [
    "Login",
    "Home",
    "Jobs",
    "New Job",
    "Job Detail",
    "Settings",
    "Change Password",
  ],
  permissions: {
    android: [
      "Internet erisimi",
      "Mikrofon",
      "Ses ve video dosyalarini okuma",
      "Android paylasim (SEND / SEND_MULTIPLE) entegrasyonu",
    ],
    ios: [
      "Mikrofon erisimi",
      "Fotograf arsivi icinden ses/video secimi",
      "Paylasilan icerigi uygulama akisina alma",
      "App Transport Security ile guvenli ag kullanimi",
    ],
  },
  privacy: [
    "iOS privacy manifest tanimli",
    "Tracking kapali",
    "Collected data types bos tanimli",
    "JWT token yalnizca guvenli depolamada tutulur",
    "Mobil istemci yalnizca kullanicinin kendi islerine erisir",
  ],
};
