export const mobileReleaseInfo = {
  appName: "Medya Zekâsı",
  version: "0.1.0",
  androidPackage: "com.medyazekasi.mobile",
  iosBundle: "com.medyazekasi.mobile",
  componentName: "MediaZekasiMobile",
  apiBaseUrl: "https://app.medyazekasi.com/api/v1",
  developer: {
    name: "Gokbilge",
    website: "https://gokbilge.com",
    email: "info@gokbilge.com",
    phone: "+90 312 440 18 20",
    phoneHref: "tel:+903124401820",
    address: "Mustafa Kemal Mah 2139 Cad IBK Plaza No:2 Çankaya Ankara",
  },
  highlights: [
    "Kullanıcı adı ve şifre ile giriş",
    "Ses ve video yükleme",
    "Uygulama içi ses kaydı",
    "YouTube linki ile iş oluşturma",
    "Başka uygulamalardan paylaşım akışı",
    "Transkript görüntüleme, kopyalama ve düzenleme",
    "Kredi bakiyesi ve hesap bilgisi",
    "Tema seçimi ve şifre değiştirme",
  ],
  screens: [
    "Login",
    "Home",
    "Jobs",
    "New Job",
    "Job Detail",
    "Settings",
    "Change Password",
  ],
  permissions: {
    android: [
      "İnternet erişimi",
      "Mikrofon",
      "Ses ve video dosyalarını okuma",
      "Android paylaşım (SEND / SEND_MULTIPLE) entegrasyonu",
    ],
    ios: [
      "Mikrofon erişimi",
      "Fotoğraf arşivi içinden ses/video seçimi",
      "Paylaşılan içeriği uygulama akışına alma",
      "App Transport Security ile güvenli ağ kullanımı",
    ],
  },
  privacy: [
    "iOS privacy manifest tanımlı",
    "Tracking kapalı",
    "Collected data types boş tanımlı",
    "JWT token yalnızca güvenli depolamada tutulur",
    "Mobil istemci yalnızca kullanıcının kendi işlerine erişir",
  ],
  storeCopy: {
    subtitle: "Kurumsal medya kayıtlarını mobile taşıyan iş akışınız",
    shortDescription:
      "Ses, video ve YouTube kayıtlarını gönderin; işlerinizi mobilde takip edin.",
    fullDescription: [
      "Medya Zekâsı, kurum içi medya işlerini mobil cihazlardan yönetmek isteyen ekipler için geliştirilmiş resmi mobil istemcidir.",
      "Kullanıcılar mevcut kurum hesaplarıyla giriş yapabilir, ses ve video dosyası yükleyebilir, uygulama içinde ses kaydı alıp iş oluşturabilir, YouTube linki gönderebilir ve kendi işlerinin durumunu takip edebilir.",
      "Tamamlanan işlerde transkript metni görüntülenebilir, kopyalanabilir ve düzenlenebilir. Ayarlar ekranında kredi bilgisi, tema seçimi ve şifre değiştirme gibi temel hesap işlemleri yer alır.",
      "Uygulama özellikle belediyeler, basın-yayın ekipleri, kamu kurumları ve saha ekipleri için hızlı iş oluşturma ve kurumsal hafıza akışına mobil erişim sağlar.",
    ],
    keywords: [
      "medya zekâsı",
      "transkripsiyon",
      "kurumsal hafıza",
      "belediye",
      "kamu",
      "ses kaydı",
      "video yükleme",
      "youtube'dan iş oluşturma",
    ],
    supportUrl: "https://medyazekasi.com/gizlilik-politikasi",
    marketingUrl: "https://medyazekasi.com/mobil-uygulama",
  },
};
